name: Sphinx check

on:
  pull_request:
    branches:
    - gh-pages

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
    - name: Install dependencies
      run: make install
    - name: Build HTML
      run: make html
    - name: Run checks
      run: make prcheck
